trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    include:
      - ansible

jobs:
  - job: build
    displayName: Build & Publish
    steps:
      - checkout: self

      - bash: |
          version="$(grep 'PIP_ANSIBLE_VERSION' ansible/Dockerfile | cut -d= -f2)"
          echo "##vso[task.setvariable variable=ansible.version]$version"
          echo "##vso[build.updatebuildnumber]$version"

          latest=""
          [[ "$(Build.SourceBranch)" == "refs/heads/main" ]] && latest="latest"
          echo "##vso[task.setvariable variable=ansible.version.latest]$latest"
        displayName: Init Variables

      - task: Docker@2
        displayName: Build
        inputs:
          containerRegistry: hub.docker.com
          repository: gstmichel/ansible
          command: build
          Dockerfile: "**/Dockerfile"
          buildContext: ansible
          tags: |
            $(ansible.version)
            $(ansible.version.latest)

      - task: Docker@2
        displayName: Publish
        inputs:
          containerRegistry: hub.docker.com
          repository: gstmichel/ansible
          command: push
          tags: |
            $(ansible.version)
            $(ansible.version.latest)
        condition: |
          and(
            succeeded(), 
            ne(variables['BuildReason'], 'PullRequest'), 
            eq(variables['Build.SourceBranch'], 'refs/heads/main')
          )
