trigger:
  branches:
    include:
      - main
      - feature/*
      - pull/*
  paths:
    include:
      - jf
      - .azdo/templates/docker-ci.azure-pipelines.yml
    exclude:
      - "*.md"

jobs:
  - template: ../../.azdo/templates/docker-ci.azure-pipelines.yml
    parameters:
      cli_name: jf
